#!/bin/bash

echo getobs start `date`
if [ ! -f /tmp/lock_getobs$1 ]; then
  touch /tmp/lock_getobs$1

  php -d memory_limit=256M ./getObsLocations.php $1 $2 $3

  rm -f /tmp/lock_getobs$1
fi
echo getobs end `date`
