#!/bin/bash

echo glosGetCaps start `date`
if [ ! -f /tmp/lock_glosGetCaps ]; then
  touch /tmp/lock_glosGetCaps

  wget 'http://tds.glos.us:8080/thredds/wms/SST/LakeSuperiorSST-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosWaterSurfaceTemperatureLakeSuperior.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/SST/LakeMichiganSST-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosWaterSurfaceTemperatureLakeMichigan.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/SST/LakeOntarioSST-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosWaterSurfaceTemperatureLakeOntario.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/SST/LakeErieSST-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosWaterSurfaceTemperatureLakeErie.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/SST/LakeHuronSST-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosWaterSurfaceTemperatureLakeHuron.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/CHL/LakeSuperiorCHL-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosChlorophyllLakeSuperior.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/CHL/LakeMichiganCHL-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosChlorophyllLakeMichigan.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/CHL/LakeOntarioCHL-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosChlorophyllLakeOntario.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/CHL/LakeErieCHL-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosChlorophyllLakeErie.getcaps.xml
  wget 'http://tds.glos.us:8080/thredds/wms/CHL/LakeHuronCHL-Agg?service=WMS&version=1.3.0&request=GetCapabilities' -O xml/glosChlorophyllLakeHuron.getcaps.xml
  wget 'http://wms.glos.us:8080/wms/HECWFS_Latest_Forecast/?service=wms&version=1.1.1&request=getcapabilities' -O xml/Currents-GLERL-LakeStClaire.getcaps.xml
  wget 'http://wms.glos.us:8080/wms/SLRFVM_Latest_Forecast/?service=wms&version=1.1.1&request=getcapabilities' -O xml/Currents-GLERL-StLawrenceRiver.getcaps.xml
  wget 'http://coastmap.com/ecop/wms.aspx?Request=GetCapabilities&SERVICE=WMS&key=999' -O xml/ecop.getcaps.xml

  rm -f /tmp/lock_glosGetCaps
fi
echo glosGetCaps end `date`
